spring:
  datasource:
    url: 
    username: 
    password: 
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 
      port: 
      password: 
server:
  port: 8080
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{requestId:-}] %logger{36} - %msg%n"
  level:
    org.lbl: DEBUG
    com.zaxxer.hikari: INFO
    org.springframework.jdbc: INFO
    org.mybatis: INFO
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
